
---
- name: Loops Playbook
  hosts: ubuntu3
  become: yes

  tasks:
  - name: Say Hello to ALL
    debug: msg="Hello {{ item }}"
    loop:
      - "Vasya"
      - "Petya"
      - "Masha"
      - "Olya"

  - name: Loop Until example
    shell: echo -n U >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("UUUU") == false

  - name: Prin Final Output
    debug:
      var: output.stdout


#  - name: Install many packaged
#    yum: name= {{ item }} state=installed
#    with_items:
#          - python
#          - tree
#          - mysql-client
