
---
- name: ansible Lesson10
  hosts: all
  any_errors_fatal : true
  become: yes

  tasks:
  - name: Task Number1
    yum: name=tree state=latest
    ignore_errors: yes

  - name: Task Number2
    shell: cat /home/ubuntu/myfile.txt
    register: results

  - name: Task Number 3
    shell: echo Privet Mir!!!
